services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.22-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" #host:container - port for applications to connect to
      - "15672:15672" #management port
    networks:
      - rabbitmq

  eureka-server:
    image: ramiroviszan/eureka-server:latest
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - spring
    depends_on:
      - zipkin
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  customer:
    image: ramiroviszan/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    networks:
      - spring
      - postgres
      - rabbitmq
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  fraud:
    image: ramiroviszan/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification:
    image: ramiroviszan/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    networks:
      - spring
      - rabbitmq
    depends_on:
      - zipkin
      - eureka-server
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  pgadmin: