server:
  port: 8082

spring:
  application:
    name: notification

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true #defaults to true
    register-with-eureka: true #defaults to true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys: #binding
    internal-notification: internal.notification.routing-key